### ISSUE TITLE
[ISSUE] False positive "A scalar of type 'x' used as an array" issue messages

### ISSUE THREAD

**Issue by menturion** [DEVSENSE/phptools-docs#185]
I am getting some false positive "A scalar of type 'x' used as an array" issue messages throughout the whole code.

The below example is a condensed example which results in a "`A scalar of type 'null' used as an array`" issue message for `$vals['key02']`. 

You can test the sensitivity of the static analysis for this example, e.g. ... 

- If you replace the value `null` in line `$vals['key01'] = null;` by an `int` value (e.g. '1') you will get "`A scalar of type 'int' used as an array`".  
- If you remove line `$vals['key01'] = $array['key01'];` the issue message disappears. 

```
function func(array $array): void
{
    $vals = [];

    if (!empty($array['key01'])) {
        $vals['key01'] = $array['key01'];
    } else {
        $vals['key01'] = null;
    }

    $vals['key02'] = [];
    if (!empty($array['key02'])) {
        $vals['key02'][] = $array['key02'];  // <-- Issue for $vals['key02']: "A scalar of type 'null' used as an array"
    }
}
```

**Comment by jakubmisek** [comment]
thank you for reporting that!

**Comment by jakubmisek** [comment]
issue fixed in the next update, thank you!

**Comment by menturion** [comment]
Good morning @jakubmisek 

I have just tested it with v1.21.11048. The issue is fixed for the above given test scenario.

However, I still get issue messages of type "A scalar of type 'x' used as an array" for the below condensed code fragment. 
In the below case a "`A scalar of type 'int' used as an array`" is shown for `$vals['key02']`: 

```
function func(array $vals): void
{
    $vals['key01'] = 1;  // or e.g. 'test', null
    
    foreach ($vals['key02'] as $val) {  // <-- Issue for $vals['key02']: "A scalar of type 'int' used as an array"
        // No code required here for this test scenario
    }
}
```

**Comment by jakubmisek** [comment]
Thank you for the test case, we'll try to fix that!

**Comment by jakubmisek** [comment]
`v1.21.11056` fixes that one! thank you, and please feel free to report any other false warning.

**Comment by menturion** [comment]
Many thanks. 
The above test case is fixed by `v1.21.11056`.

Below is another test case: 

```
function func(array $vals): void
{
    $vals['custom'] = 'custom';  // <-- Only sensitive to strings. The issue message disappears if int or null. 

    foreach ($vals['options'] as $options) {
        foreach ($options as $option) {  // <-- False positive for $options: A scalar of type 'string' used as an array PHP(PHP0409)
            // ...
        }

        $values = array_values($options);  // <-- False positive for $options: Argument '1' passed to array_values() is expected to be of type array, string givenPHP(PHP0406)
    }
}
```

**Comment by jakubmisek** [comment]
thank you! the last one is fixed in `v1.21.11076`. Please feel free to post any other test cases!

**Comment by menturion** [comment]
It seems to be fixed. Currently, I do not get any further issue messages of this kind.

**Comment by jakubmisek** [comment]
awesome! Thank you very much for your test cases.

**Comment by menturion** [comment]
Hi,

since the latest version `1.26.11866 (January 03, 2023)` I am getting a huge number (> 200) of "A scalar of type 'x' used as an array" issues again. 

Is this a regression?

**Comment by jakubmisek** [comment]
@menturion thank you, this looks like a regression. But should be fixed now.

Do you have any specific test case, so we can make sure this won't happen again?

**Comment by menturion** [comment]
This issue has already been fixed in one of the subsequent versions.

**Comment by jakubmisek** [comment]
thank you @menturion !

**Comment by jakubmisek** [comment]
I think we have overengineered type inferring of arrays, and it causes these weird cases; 

We're subsequently cleaning this up. Any test case helps. Thank you for reporting that.
