### ISSUE TITLE
Opening file with enum crashes language server

### ISSUE THREAD

**Issue by still-dreaming-1** [DEVSENSE/phptools-docs#385]
If I open a file that defines an enum, the language server crashes.

I'm on php 8.2 with extension pre-release v1.38.13753. The problem seemed to start right after the last update.

**Comment by jakubmisek** [comment]
Thank you for reporting the issue, fixing right now.

**Comment by jakubmisek** [comment]
fixed in `1.38.13759`

thank you again for noticing!

**Comment by still-dreaming-1** [comment]
I'm on v1.41.14263 and I still have the problem. I have only tested it with functions that are not in any namespace if that makes any difference.

**Comment by still-dreaming-1** [comment]
Please ignore the comment I added here. I posted it in the wrong place and then deleted it. This issue is still resolved for me, thank you.
