### ISSUE TITLE
Shows random garbage suggestions when opening [], Enter results in selecting one of them

### ISSUE THREAD

**Issue by php4fan** [DEVSENSE/phptools-docs#470]
Often I want to call a function and pass an associative parameter as the only argument, for example:

```
  $this->doSomething([
      'foo' => 123,
      'bar' => 456
  ]);
```

So, I start by typing the function name, the opening parenthesis `(`, and the opening square bracket for the associative array `[`, and then I hit Enter to go to a new line.

As expected, the IDE autocloses both the parenthesis and the bracket, so after hitting Enter I should have:

```
  $this->doSomething([
  ]);
```
and my cursor would be right before the closing `]`. I should be good to go to hit Enter one or a couple more times, and then start filling the array with keys and values.

**However**, the moment I type the opening `[` (which immediately causes the corresponding `]` to be autocompleted as expected), the IDE also decides, for some reason, to show me a bunch of random suggestions that seems to be a complete list of all existing fully-qualified class names ever, or something equally useless in this context:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/45ee8894-9d7b-4944-a38a-a4bf6bc1ab7c)

Most of the times, I hit Enter before I even realize that that list has shown up, because I was going to hit Enter anyway; and the result is that I select the first item in the list, which I bet there is no real-life use case more common than one in 10 to the trillionth where it could be what one may want in such a context.

Obviously if I do see the list pop up in time, I know that I can hit Esc to make the stupid list go away, and then hit Enter to type the newline. But most of the times, I hit Enter before I realize.

I think there are two issues here:
1. That the suggested list that pops up is very unlikely to be useful in any reasonably conceivable real-life scenario
2. Even if there was a sensible list of suggestions to come up with, selecting the first item in the list should always require something more than just hitting Enter (e.g. using the down arrow and _then_ hitting Enter), at least when entering an actual newline is a very sensible option as it is in this case.

**Comment by php4fan** [comment]
Here's the same issue in a different context:

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/401277b3-1de4-4439-9ba5-99f29a106669)

Here the list of suggestions is different, but I'm pretty sure it's utterly useless too. Actually I think it's worse than the previous one. Here I don't think you could make up a theoretical example where any of the proposed options could even be legal, let alone likely to be useful.

But again, even if the list of suggestions were sensible, the bigger issue is that the first one is immediately selected by just hitting enter.

**Comment by jakubmisek** [comment]
Thank you for reporting this;

Suggestions after `[` is really too eager;

We have fixed this in the pre-release, and preparing full release soon.

**Comment by jakubmisek** [comment]
fixed in the latest update, thanks!

**Comment by php4fan** [comment]
I'm still seeing this, at least in some contexts.

![image](https://github.com/DEVSENSE/phptools-docs/assets/13969584/678edf39-c559-4bd5-8c4e-4e26a27c940b)

**Comment by php4fan** [comment]
Still seeing it in some cases

![image](https://github.com/user-attachments/assets/2f22b67b-fa6b-4c35-8cc1-4f214ae60f65)

**Comment by jakubmisek** [comment]
You're right, it seems we popup completion of everything inside [''] - will be fixed!

**Comment by jakubmisek** [comment]
Fixed in the yesterday's pre-release, thanks!
