### ISSUE TITLE
Laravel Blade syntax problems with comments

### ISSUE THREAD

**Issue by wfern** [DEVSENSE/phptools-docs#486]
Syntax highlight broke when commenting blade tags or directives, but still ok if comment is html only.

It happens with both comment syntax, blade: `{{-- --}}` and html: `<!-- -->`. 

Check the code after the comment:

Example without comments:
![image](https://github.com/DEVSENSE/phptools-docs/assets/4096003/3755cb4a-a23d-48be-bb4d-51f9c9c2a286)

After commenting blade directive, line 8:
![image](https://github.com/DEVSENSE/phptools-docs/assets/4096003/489efbae-4bff-462e-bbdd-261c37d0aeb6)

After commenting html elements, line 9:
![image](https://github.com/DEVSENSE/phptools-docs/assets/4096003/999bf0f1-8535-47d7-96b6-c5ce8eb65a2c)

Code example: 
```blade
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    @yield('title')
    <link rel="icon" type="image/png" sizes="16x16" href="/images/icons/favicon-16x16.png">
    <link rel="mask-icon" href="/images/icons/safari-pinned-tab.svg" color="#000">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap">
</head>

<body>
    <div>
        <h1>Test</h1>
        @yield('content')
    </div>
</body>

</html>
```

**Comment by jakubmisek** [comment]
Thank you for the detailed issue;

Will be fixed in the upcoming pre-release update (and then the full update).

**Comment by wfern** [comment]
@jakubmisek Taking advantage of the issue to ask a question, would you be able to add an option to disable just the laravel blade syntax highlight?

In my case, I've been using an old extension called "Laravel Blade Snippets" for years and it works really well for this function, so in case of bugs with the new function of your extension, we can disable it without having to downgrade (my case now) . In this case, I need to downgrade because they collide and there is no way to choose which extension to use for the syntax highlight in vscode.
​

**Comment by jakubmisek** [comment]
This should be already fixed (maybe it gets released in a few hours..), anyways,

there is no setting for disabling the highlighting - vscode does not provide any way to do that.

You can manually patch our extension's package.json to get rid of it if it would work for you? I can provide steps how to do that.

**Comment by Reund0** [comment]
> This should be already fixed (maybe it gets released in a few hours..), anyways,

no, it is not fixed. when I'm working on `.blade` files I disable the plugin to let the `Laravel-blade-snippet` do the work instead.

**Comment by jakubmisek** [comment]
@Reund0 have you tried the pre-release version (1.44.14984)? It is not in the release yet.

**Comment by jakubmisek** [comment]
we have released stable update with the fix

thank you!

**Comment by Reund0** [comment]
@jakubmisek  I updated the extension to  version `v1.44.14991` that released one hour ago. but the problem is still not fixed.
I re-install the extension and reload the vscode but the comments are like this:
![image](https://github.com/DEVSENSE/phptools-docs/assets/52788288/1e854917-ce5b-4a07-99ad-006385b7bd41)
but if I disable it, the `laravel-blade-snippet` handle it very well:
![image](https://github.com/DEVSENSE/phptools-docs/assets/52788288/9ad121a6-ddd1-4f45-986c-da7dbd3d04a3)
but if I disable the `phptools`, I lose so many things in other php files.

**Comment by Reund0** [comment]
@jakubmisek is there a way to prevent `phptools` from accessing to `.blade.php` files? You said something earlier about patching to get rid of this part.

**Comment by jakubmisek** [comment]
@Reund0 I have the right opposite :/

with `phptools` only:
![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/5ea54515-0978-4c66-b873-2286cb26005b)

with `onecentlin.laravel-blade` (and phptools)
![image](https://github.com/DEVSENSE/phptools-docs/assets/842150/e494e971-a375-4315-b26a-ab223bdf0cd9)

So we are probably breaking the other blade language highlighting, while our own works alone works ok.

I'll take a look at it.

**Comment by jakubmisek** [comment]
Preparing an update that disables our blade highlighting if there is another 3rd party blade grammar.

**Comment by jakubmisek** [comment]
Fixed in the latest update.

We don't integrate into 3rd party `blade` language grammar now. However, for complete features (and future enhancements to our blade completions), you can switch to the `PHP` language (as depicted above).
