### ISSUE TITLE
PHP6609 error

### ISSUE THREAD

**Issue by Infiland** [DEVSENSE/phptools-docs#635]
There is an error that occurs in the extension where it reports that the class name should be lowercase, or the filename should be the same as the class. Using PHP 8.3

However, it still throws this error in the vscode IDE.

![image](https://github.com/user-attachments/assets/79c60f0a-f52b-4ff0-b9b0-0a3fda38a09b)

Autoload is defined in index.php

![image](https://github.com/user-attachments/assets/21b13237-4c8c-497b-9693-b3edf5f0ec2e)

This is the composer.json file which autoloads all classes in the Src folder

![image](https://github.com/user-attachments/assets/29c9de0f-12de-4ebd-9a79-d8015c8aa02e)

Running index.php doesn't print any errors or exception in the browser or console.
This exception seems to only appear in vscode, but only if the PHP extension is enabled.

**Comment by jakubmisek** [comment]
Thank you for reporting that!

It seems we got the letter casing wrong, and hence we misreport the problem.

Wll be fixed!

**Comment by jakubmisek** [comment]
Are you on windows/linux or mac?

**Comment by Infiland** [comment]
> Are you on windows/linux or mac?

I am on Windows, I can list my PC Specs but I am not sure if it's relevant.

**Comment by jakubmisek** [comment]
For me: there are a few related issues with VSCode and LSP implementation:

https://github.com/microsoft/language-server-protocol/issues/1263
https://github.com/microsoft/vscode/issues/137256

**Comment by jakubmisek** [comment]
so far of what we've tested, the issue should be fixed in the upcoming update.

**Comment by Infiland** [comment]
> so far of what we've tested, the issue should be fixed in the upcoming update.

Great! I will let you know if the issue is resolved in the next update

**Comment by Jack-Mutsers** [comment]
From what I could see the last update was 3 days ago, but I'm still having this problem where the filename is the exact same as the class name and if I copy the file over to another folder (from /libraries to /models for example) then there are no problems, is this a caching issue where it remembers an old version or something with the lowercase filename?

P.S.
personally, I am using VSCode on MacOs

**Comment by Jack-Mutsers** [comment]
<img width="631" alt="image" src="https://github.com/user-attachments/assets/e251805a-6f11-40f0-bc6c-f8c93a988908">
these 2 files are an exact copy of one another, but only one gives me the error: Class name Optimizer does not match PSR autoload pattern. It is expected to be optimizer, or the file name should be Optimizer.php.PHP(PHP6609)

**Comment by jakubmisek** [comment]
Thank you for the update; we couldn't repro the issue after the update, yet. Are there any particular steps to reproduce the issue?

**Comment by Jack-Mutsers** [comment]
VS studio

**Comment by jakubmisek** [comment]
Right, it just seems that our extension does not get the event about the change. We'll try that on MacOs

**Comment by jakubmisek** [comment]
After digging through the issue, we found several related problems in VSCode itself — it simply does not respect the letter casing after the rename. Therefore the extension (our extension) is not getting the correct information. It also uses incorrect letter casing right after opening the workspace. 

I'm trying to work around it ... Meanwhile, I'll report the other issues to MS.

Related issue: https://github.com/microsoft/vscode-languageserver-node/issues/1186

**Comment by alex-elivate** [comment]
Is there a way to reset this or some cache I can clear?  I tried renaming the file in the finder on MacOS, renaming it in VSCode, quiting VSCode, disabling the extention, then reenabling it and this syntax highlighting persists through all of this.
<img width="1888" alt="Screenshot 2024-12-03 at 6 10 32 PM" src="https://github.com/user-attachments/assets/351b93d4-0a4b-4733-b7c7-10b204503b41">

**Comment by jakubmisek** [comment]
@alex-elivate thank you for pointing this out!

I'm aware this is still an issue in some cases; VSCode does not respect the letter casing and we falsely report an error ...

We're working on a fix.

**Comment by rolland97** [comment]
Hi, I have the same problem as well. However, mine only occurs when I start with a lowercase file name, delete the file, and then recreate it with an uppercase file name.

**Comment by EnesK311** [comment]
@rolland97 I have the exact same problem right now, did you find a fix for this or a workaround?

**Comment by jakubmisek** [comment]
Thank you for the steps and for reporting the issue; still working on it. I appreciate any information.

**Comment by EnesK311** [comment]
@jakubmisek I have the problem on MacOs, I created a controller in Laravel with php artisan make:controller and I accidentally gave it the name Authcontroller instead of AuthController and now I get errors even tho I adjusted it everywhere, deleted the file remade it, renamed it in finders and renamed it in vscode aswell.

**Comment by jakubmisek** [comment]
It is caused by (the misbehavior) of the VSCode API
- https://github.com/microsoft/vscode/issues/121106
- https://github.com/microsoft/language-server-protocol/issues/1263

We'll need to do some additional workarounds to fix that.

**Comment by jakubmisek** [comment]
We'll (temporarily) disable the case-sensitive check since there are multiple issues with letter casing in file names. Possible workaround would be noticeably inefficient.

This change will be included in the very next update.
