### ISSUE TITLE
Support for class-string with templating

### ISSUE THREAD

**Issue by leoasis** [DEVSENSE/phptools-docs#746]
The `class-string` docstring (used commonly with Psalm and PHPStan tools) doesn't seem to be supported, especially when using it with template types. I tried using it in combination with generics and it doesn't seem to be interpreted, making the resulting variable untyped.

Example:

```php
/**
 * @template T
 */
class Foo {
  public function __construct(string $classname)
  {
  }
}
```

```php
/**
   * @template T
   * @param class-string<T> $class
   * @return Foo<T>
   */
  public function getFoo(string $class): Foo
  {
      return new Foo($class);
  }

  public test(): void
  {
      $var = $this->getFoo(SomeClass::class); // <-- I'd expect $var to be of type `SomeClass` and autocomplete methods
  }
```

Is this something this extension would aim to support? If not intended for this extension to support all Psalm docstring type extensions, which would be a recommended extension to support these?

**Comment by jakubmisek** [comment]
Thank you for the issue.

`class-string<T>` is supported, but in your example, the return value is not supposed to be `SomeClass`, but `Foo<SomeClass>` which has no members except for `__construct`.

![image](https://github.com/user-attachments/assets/64c38fcc-eb41-4ab3-acf0-c5003e3aa248)

![image](https://github.com/user-attachments/assets/4b8d4700-0323-420e-9f26-36617fde5586)


Only thing I see, is that there is a syntax error in `public test(): void` (missing `function`) which may confuse IntelliSense.

**Comment by leoasis** [comment]
Oh my bad, for some reason I tried this out and it wasn't working, it seems I simplified the example too much. Turns out the issue seems to be really that the @inheritDoc is not properly being understood. So maybe this is the issue. If I explicitly set the @return T in the subclass method, it works fine.

Consider this example:

```php
/**
 * @template T
 */
class Foo
{
    public function __construct(string $classname)
    {
    }

    /**
     * @return T
     */
    public function get()
    {
        return new \stdClass();
    }
}

/**
 * @template T
 * @extends Foo<T>
 */
class Bar extends Foo
{
    public function __construct(string $classname)
    {
    }

     /**
     * @inheritDoc
     */
    public function get()
    {
        return new \stdClass();
    }
}
```

```php
  /**
   * @template T
   * @param class-string<T> $class
   * @return Foo<T>
   */
    public function getFoo(string $class): Foo
    {
        return new Foo($class);
    }

    /**
   * @template T
   * @param class-string<T> $class
   * @return Bar<T>
   */
    public function getBar(string $class): Bar
    {
        return new Bar($class);
    }
```

```php
$var = $this->getFoo(\User::class)->get(); // works fine
$var2 = $this->getBar(\Tumblelog::class)->get(); // doesn't work.
```

**Comment by jakubmisek** [comment]
Fixed in the next update, thanks!

**Comment by leoasis** [comment]
I just tested this in the latest release but it seems it's not yet fixed. In the above example, I see `$var2` is inferred to be of type `stdClass`, but it should be of type `Tumblelog`)

**Comment by jakubmisek** [comment]
Thank you for testing the update; maybe my test case was not copied properly, but it gives me the expected results:

![image](https://github.com/user-attachments/assets/9ade800e-f4a9-481d-af69-99b83841eb2e)

**Comment by leoasis** [comment]
I'm using `1.55.16685` and I still see the problem 🤔 :

![image](https://github.com/user-attachments/assets/23504b66-b2ea-44ab-b219-9dfa4005c4f2)

![image](https://github.com/user-attachments/assets/a3c208d5-7acc-4eb8-9755-01d8a52457c6)

**Comment by jakubmisek** [comment]
Thank you for the update; we'll do more testing.

May I ask what extension you use for those additional diagnostics? They seem very strict/intrusive.

**Comment by leoasis** [comment]
@jakubmisek wanted to let you know that I've noticed this is now fixed in the latest version of the plugin. Not exactly sure what changed, but seems it works fine now! Thanks!

**Comment by jakubmisek** [comment]
@leoasis thank you for keeping me updated!

Yes, we have been tuning the type inference for various edge cases like this one. I;m glad it resolved this issue.
